# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative '../common'

Vagrant.configure("2") do |config|
  config.vm.box = Common::OS_NAME
  config.vm.box_version = Common::OS_VERSION
  config.vm.hostname = "jumpbox"
  config.vm.network "public_network", bridge: "enp2s0"
  config.vm.network "private_network", ip: "10.200.1.2", virtualbox__intnet: true

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.cpus = 2
    vb.memory = "1024"
  end

  config.vm.disk :disk, size: "10GB", primary: true

  config.vm.provision "shell", inline: Common::SHELL_SCRIPTS
end
